#Recuerda modificar este fichero para obtener tus propios credenciales. 
#Si usas capistrano en tu deploy puedes crearte el fichero app/shared/admin.yml con los credenciales
#y luego en la receta de capistrano automatizar un enlace simbólico que pise este fichero.
username: admin
password: "1234"
